// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCrdCzoIqxERfn1w6MAClhj7Hn-mblVQo',
    appId: '1:244771928028:web:ef80fc5b6c2f4d9b52c119',
    messagingSenderId: '244771928028',
    projectId: 'bmi-auth',
    authDomain: 'bmi-auth.firebaseapp.com',
    storageBucket: 'bmi-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmJRwSMmkFP77a8cEjjK4az4Xbw0hLlho',
    appId: '1:244771928028:android:37bca1df07b948e952c119',
    messagingSenderId: '244771928028',
    projectId: 'bmi-auth',
    storageBucket: 'bmi-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRQNUHl7H_cRQbY-V3oAlEoUGqxsdymqc',
    appId: '1:244771928028:ios:b3512156535016da52c119',
    messagingSenderId: '244771928028',
    projectId: 'bmi-auth',
    storageBucket: 'bmi-auth.appspot.com',
    iosClientId: '244771928028-mb9ev0d5v1phb1t6ek06253ulq23ksm8.apps.googleusercontent.com',
    iosBundleId: 'com.example.bmi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRQNUHl7H_cRQbY-V3oAlEoUGqxsdymqc',
    appId: '1:244771928028:ios:4c2b6762bb045ce452c119',
    messagingSenderId: '244771928028',
    projectId: 'bmi-auth',
    storageBucket: 'bmi-auth.appspot.com',
    iosClientId: '244771928028-q769974tfdu0lu4suvcvslqpjrpqcju7.apps.googleusercontent.com',
    iosBundleId: 'com.example.bmi.RunnerTests',
  );
}
